name: Update README Stats

on:
  schedule:
    - cron: "0 * * * *" # updates hourly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          token: ${{ secrets.PAT_1 }}
